#* ~/.config/starship.toml

#* SOURCES
#* https://starship.rs/config
#* https://starship.rs/presets/nerd-font.html##configuration

#  î‰® YoncÃ© all on his mouth like liquor
# â”Œï•ï‚„ user ï„ ï›ƒ hostname ï„ î—¾ ~/full/directory/path ï„ ïˆ branch â†‘1 â†“1 {1} +1 â€¢1 âŒ€1 ï€ ï€Œ             [ ïº 00:00 ]  ï‰€ 100%â†“
# â””ï„ cd .bash-it/themes/yonce

# git-status-demo on ï˜ main â†‘1â†“1 +1 !1 âŒ€1 [1]  î™” 1 ERROR  â¯                                  âš¡78% ïº 00:11:57
# git-status-demo on ï˜ main â†‘1â†“1 +1 !1 âŒ€1 [1] via îœ˜ v18.18.2  ï¢ 127 NOTFOUND  â¯
# webapp on ó°Š¢ ui-generator-hooks â†‘4039â†“5 +1 !1 âŒ€73 {1} took â± 1m34s â¯                       âš¡78% ïº 17:50:56

#* DEBUG via:
#* starship explain
#* STARSHIP_LOG=trace starship timings

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

#* Timeout for commands executed by starship (ms)
command_timeout = 10000

#* newline between commands
# add_newline = false

#* opt-in for individual modules (e.g., aws, docker, gcloud, nodejs, python)
format = """$all"""
right_format = """$battery$time"""

# format = """
# [â•­â”€accountsâ”€âœâ‡‰â¯>](bold blue) $username$gcloud$aws$kubernetes
# [â”£â”€networkâ”€â”€âœâ‡‰â¯>](bold yellow) $localip
# [â”£â”€systemâ”€â”€â”€âœâ‡‰â¯>](green) $time$status$cmd_duration$hostname$memory_usage$jobs$battery
# [â”£â”€projectâ”€â”€âœâ‡‰â¯>](bold red) $directory$rust$package$golang$terraform $docker_context
# [â”£â”€gitâ”€â”€â”€â”€âœâ‡‰â¯>](bold blue)$git_branch$git_status$git_commit
# [â”£â”€metricsâœâ‡‰â¯>](bold red)$git_metrics
# [â•°â”€cliâ”€âœâ‡‰â¯>](bold green)$character
# """

#* A continuation prompt that displays two filled in arrows
# continuation_prompt = 'â–¶â–¶ '

[username]
disabled = true

[hostname]
ssh_only = true
ssh_symbol = "ğŸŒ "
disabled = false

[battery]
full_symbol = "ó°¹ "
charging_symbol = "ó°‚ "
discharging_symbol = "ó°‚ "
unknown_symbol = "âš¡"
empty_symbol = "ï–"
disabled = false

#* "red" style when capacity is between 0% and 20%
[[battery.display]]
threshold = 20
style = "red"

#* "yellow" style when capacity is between 20% and 50%
[[battery.display]]
threshold = 50
style = "yellow"

#* "green" style when capacity is between 70% and 100%
[[battery.display]]
threshold = 100
style = "green"

#* Replace the "â¯"
[character]
# success_symbol = "[âœ](bold green)"
# error_symbol = "[âœ–](bold red)"

#* Show command duration over 10,000 milliseconds (=10 sec)
[cmd_duration]
# min_time = 500
format = "took [â± $duration]($style) "

#* truncation length works backwards (i.e., cwd > parent > parent ...)
[directory]
read_only = "ï ½"
truncation_length = 5
# truncation_symbol = "â€¦/"
truncate_to_repo = true

#* Keep in mind that the order matters. For example:
#* "Important Documents" = " ó°ˆ™ï„ª "
#* will not be replaced, because "Documents" was already substituted before.
#* So either put "Important Documents" before "Documents" or use the substituted version:
#* "Important ó°ˆ™ " = " ó°ˆ™ï„ª "
[directory.substitutions]
"~/Documents" = "ó°ˆ™ "
"~/Downloads" = "ï€™ "
"~/Movies" = "ó°¿ "
"~/Music" = "ï€ "
"~/Pictures" = "ï€¾ "
"~/@Projects" = "â™¥ "
"~/@Inbox" = "ï€œ "
"~/@WIP" = "ó°’¡ "
# "~" = "ó°‹œ "
# "/" = " î‚± "

[git_branch]
symbol = "ï˜ "

[git_commit]
commit_hash_length = 8

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[îŠ› PICKING](bold red)'
rebase = "REBASING"
merge =	"MERGING"
revert = "REVERTING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
disabled = false

[git_status]
conflicted = "âœ² " # ï€¤
ahead = "[â†‘](bold green)${count} " # â‡¡
behind = "[â†“](bold red)${count} " # â‡£
diverged = "[â†‘](bold green)${ahead_count}[â†“](bold red)${behind_count} " # ï§¡
untracked = "âŒ€${count} "
stashed = '\[${count}\] '
modified = "[!](bold yellow)${count} "
staged = "[+](bold green)${count} "
renamed = "Â»${count} "
deleted = "[âœ–](bold red)${count} " # âœ˜
format = "$conflicted$ahead_behind$staged$modified$untracked$stashed$deleted$renamed"

[git_metrics]
added_style = 'bold blue'
deleted_style = "bold red"
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '
# format = '([ Added: +$added]($added_style))([ Deleted: -$deleted]($deleted_style) )'
disabled = false

[memory_usage]
symbol = "ó°› "
disabled = false

[time]
format = "[ïº  $time]($style) "
disabled = false

[nodejs]
disabled = true

#* makes prompt a single line
[line_break]
disabled = true

[localip]
ssh_only = true
disabled = false

[sudo]
style = 'bold green'
symbol = 'ï‚„ '
disabled = false

[package]
symbol = 'î¬© '
disabled = true

#* Clear visibility for exit codes
[status]
style = "bg:red"
symbol = " î™” "
not_found_symbol = " ï¢ "
not_executable_symbol = " ï "
format = '[$symbol$status $common_meaning$signal_name$maybe_int ]($style) '
map_symbol = true
disabled = false
